In [93]:
#Jeremiah Hsieh Machine Learning Homework 5 linear discriminant analysis
#i guess i'm assuming that there are 3 features so i read them as columns?
#i suppose that has to be the case since otherwise the number of features tracked is not the same accross the postive and negative sets
#i accidentally wasted a bunch of time thinking tha the data was read vertically
import numpy as np
import sklearn 

Xp = np.array([
            [4, 2, 2, 3, 4, 6, 3, 8], 
            [1, 4, 3, 6, 4, 2, 2, 3],
            [0, 1, 1, 0, -1, 0, 1, 0]
             ])
Xn = np.array([
            [9, 6, 9, 8, 10], 
            [10, 8, 5, 7, 8],
            [1, 0, 0, 1, -1]
             ])





#1  class specific means
#calculate mean of each column?



autoXpmean = Xp.mean(1)

height = autoXpmean.shape[0]
#apparently the tuple is only a single value for 1xN arrays
length = 1 #autoXpmean.shape[1]
shapedXpmean = autoXpmean.reshape(length, height)

print("\nautomatically calculated column vector mean of Xp: ")
print(shapedXpmean)

autoXnmean = Xn.mean(1)
shapedXnmean = autoXnmean.reshape(length, height)
print("\nautomatically calculated column vector mean of Xn: ")
print(shapedXnmean)




#2 manually calculated mean
manualXpmean = []
#loop through columns
for x in range(0, Xp.shape[0]):
    total = 0
    #loop through rows
    for y in range(0, Xp.shape[1]):
        #sum
        total += Xp[x][y]
    #mean
    manualXpmean.append(total/Xp.shape[1])
    
print("\nmanually calculated column vector mean of Xp: ")
print(manualXpmean)



manualXnmean = []
#loop through columns
for x in range(0, Xn.shape[0]):
    total = 0
    #loop through rows
    for y in range(0, Xn.shape[1]):
        #sum
        total += Xn[x][y]
    #mean
    manualXnmean.append(total/Xn.shape[1])
    
print("\nmanually calculated column vector mean of Xn: ")
print(manualXnmean)



#3 automatic covariance
#shouldn't covariance be size equivlent to rowsize?
autoXpcov = np.cov(Xp) #,  rowvar = False)
print("\nautomatically calculated covariance Xp matrix")
print(autoXpcov)

autoXncov = np.cov(Xn) #,  rowvar = False)
print("\nautomatically calculated covariance Xn matrix")
print(autoXncov)


#4 manual covariance
#center by subtracting mean 
centeredXp = Xp.astype(float).copy()
for x in range(0, centeredXp.shape[0]):
    #loop through rows
    for y in range(0, centeredXp.shape[1]):
        #subtract column mean
        centeredXp[x][y] -= manualXpmean[x]
        
#print("\nmanually calculated centered Xp matrix")
#print(centeredXp)

#calculate covariance using centered matrix
manualXpcov = np.zeros((Xp.shape[0], Xp.shape[0]))
for x in range(0, Xp.shape[0]):
    
    #loop through rows
    for y in range(0, Xp.shape[0]):
        total = 0
        #sum corresponding columns
        for inner in range(0, Xp.shape[1]):
            total += (centeredXp[x][inner] * centeredXp[y][inner])
        #append final result to covariance matrix
        manualXpcov[x][y] = total/(Xp.shape[1]-1)
print("\nmanually calculated covariance Xp matrix")
print(manualXpcov)



#center by subtracting mean 
centeredXn = Xn.astype(float).copy()
for x in range(0, centeredXn.shape[0]):
    #loop through rows
    for y in range(0, centeredXn.shape[1]):
        #subtract column mean
        centeredXn[x][y] -= manualXnmean[x]
        
#print("\nmanually calculated centered Xn matrix")
#print(centeredXn)

#calculate covariance using centered matrix
manualXncov = np.zeros((Xn.shape[0], Xn.shape[0]))
for x in range(0, Xn.shape[0]):
    
    #loop through rows
    for y in range(0, Xn.shape[0]):
        total = 0
        #sum corresponding columns
        for inner in range(0, Xn.shape[1]):
            total += (centeredXn[x][inner] * centeredXn[y][inner])
        #append final result to covariance matrix
        manualXncov[x][y] = total/(Xn.shape[1]-1)
print("\nmanually calculated covariance Xn matrix")
print(manualXncov)



#5 automatic between class scattering
#Sb = (n+n- / n^2) (mean+ - mean-) * (mean+ - mean-)^T
#just append negative data to end of positive data?
#n+ = 8, n- = 5, n = 13?
# (8*5) / (13^2) = .23668639053
#positive and negative mean matrices are not same size?
#oh i see i was reading data the wrong direction
#for some reason it's not making matrix despite it being 3x1 * 1x3
#oh i see i forgot it was outer product not dot product

Xtotalsize = Xp.shape[1] + Xn.shape[1]
automeandiff = autoXpmean - autoXnmean
automeanproduct = np.outer(automeandiff, automeandiff)
#automeanproduct = automeandiff.reshape(length, height).dot(automeandiff) #np.dot(meandiff.reshape(length, height), meandiff)
autoSb = ((Xp.shape[1] * Xn.shape[1]) / (Xtotalsize**2)) * automeanproduct
print("\nautomatic between class scattering")
print(autoSb)



#rank - maximum number of linearly independent column vectors in the matrix



#6 manual between class scattering
manualmeandiff = []
for i in range(0, len(manualXpmean)):
    manualmeandiff.append(manualXpmean[i] - manualXnmean[i])

manualmeanproduct = np.zeros((len(manualmeandiff), len(manualmeandiff)))
for x in range(0, len(manualmeandiff)):
    for y in range(0, len(manualmeandiff)):
        manualmeanproduct[x][y] = manualmeandiff[x] * manualmeandiff[y]
manualSb = ((Xp.shape[1] * Xn.shape[1]) / (Xtotalsize**2)) * manualmeanproduct
print("\nmanual between class scattering")
print(manualSb)


#7 automatic within class scattering

automaticXpwithin = ((Xp.shape[1] / Xtotalsize) * np.cov(Xp))
automaticXnwithin = ((Xn.shape[1] / Xtotalsize) * np.cov(Xn))
autoSw = automaticXpwithin + automaticXnwithin
print("\nautomatic within class scatter:")
print(autoSw)




#8 manual within class scattering
#not really any different since i didnt see an automatic function for numpy since manualXpcov is same values as autoXpcov
#((n+ / n) * S+ ) + ((n- / n) * S-)
#S+ and S- are the covariance matrices

manualXpwithin = ((Xp.shape[1] / Xtotalsize) * manualXpcov)
manualXnwithin = ((Xn.shape[1] / Xtotalsize) * manualXncov)
manualSw = manualXpwithin + manualXnwithin

print("\nmanual within class scatter:")
print(manualSw)





#9 automatic LDA projection, eigenvalue decomposition
#multiply Sb and Sw together and solve for eigenvalues?

autoeigenvalues, autoeigenvectors = np.linalg.eig(autoSb * autoSw)

print("\nautomatic eigenvalues")
print(autoeigenvalues)
print("\nautomatic eigenvectors")
print(autoeigenvectors)

#10 manual LDA projection, eigenvalue decomposition
#TBD


#11 binary LDA  mybLDA_train
def mybLDA_train(Xp, Xn):
    
    autoXpmean = Xp.mean(1)
    height = autoXpmean.shape[0]
    length = 1 
    shapedXpmean = autoXpmean.reshape(length, height)
    
    

    autoXnmean = Xn.mean(1)
    shapedXnmean = autoXnmean.reshape(length, height)

    
    
    autoXpcov = np.cov(Xp) 


    autoXncov = np.cov(Xn) 

    
    
    Xtotalsize = Xp.shape[1] + Xn.shape[1]
    automeandiff = autoXpmean - autoXnmean
    automeanproduct = np.outer(automeandiff, automeandiff)
    
    autoSb = ((Xp.shape[1] * Xn.shape[1]) / (Xtotalsize**2)) * automeanproduct

    
    
    automaticXpwithin = ((Xp.shape[1] / Xtotalsize) * np.cov(Xp))
    automaticXnwithin = ((Xn.shape[1] / Xtotalsize) * np.cov(Xn))
    autoSw = automaticXpwithin + automaticXnwithin

    

    autoeigenvalues, autoeigenvectors = np.linalg.eig(autoSb * autoSw)

    
    
    return autoeigenvalues



#12 mybLDA_classify 
#not entirely sure how to do this
def mybLDA_classify(X, v):
    return v


#13 combine the previous 2

vector = mybLDA_train(Xp, Xn)

data = np.array([
            [1.3, 2.4, 6.4, 2.2, 3.4, 3.2], 
            [8.1, 7.6, 2.1, 1.1, 0.5, 7.4],
            [-1, 2, 3, -2, 0, 2]
             ]) 
result = mybLDA_classify(data, vector)


#sklearn LDA comparison?



automatically calculated column vector mean of Xp: 
[[4.    3.125 0.25 ]]

automatically calculated column vector mean of Xn: 
[[8.4 7.6 0.2]]

manually calculated column vector mean of Xp: 
[4.0, 3.125, 0.25]

manually calculated column vector mean of Xn: 
[8.4, 7.6, 0.2]

automatically calculated covariance Xp matrix
[[ 4.28571429 -0.85714286 -0.71428571]
 [-0.85714286  2.41071429 -0.17857143]
 [-0.71428571 -0.17857143  0.5       ]]

automatically calculated covariance Xn matrix
[[ 2.3  -0.05 -0.35]
 [-0.05  3.3   0.35]
 [-0.35  0.35  0.7 ]]

manually calculated covariance Xp matrix
[[ 4.28571429 -0.85714286 -0.71428571]
 [-0.85714286  2.41071429 -0.17857143]
 [-0.71428571 -0.17857143  0.5       ]]

manually calculated covariance Xn matrix
[[ 2.3  -0.05 -0.35]
 [-0.05  3.3   0.35]
 [-0.35  0.35  0.7 ]]

automatic between class scattering
[[ 4.58224852e+00  4.66035503e+00 -5.20710059e-02]
 [ 4.66035503e+00  4.73979290e+00 -5.29585799e-02]
 [-5.20710059e-02 -5.29585799e-02  5.91715976